/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCvBuilderChatRouteImport } from './routes/api.cv-builder-chat'
import { Route as ApiCvChatRouteImport } from './routes/api.cv-chat'
import { Route as CvsCvIdRouteImport } from './routes/cvs.$cvId'
import { Route as CvsNewRouteImport } from './routes/cvs.new'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as ApiCvsCvIdPdfRouteImport } from './routes/api/cvs.$cvId.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvBuilderChatRoute = ApiCvBuilderChatRouteImport.update({
  id: '/api/cv-builder-chat',
  path: '/api/cv-builder-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvChatRoute = ApiCvChatRouteImport.update({
  id: '/api/cv-chat',
  path: '/api/cv-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CvsCvIdRoute = CvsCvIdRouteImport.update({
  id: '/cvs/$cvId',
  path: '/cvs/$cvId',
  getParentRoute: () => rootRouteImport,
} as any)
const CvsNewRoute = CvsNewRouteImport.update({
  id: '/cvs/new',
  path: '/cvs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvsCvIdPdfRoute = ApiCvsCvIdPdfRouteImport.update({
  id: '/api/cvs/$cvId/pdf',
  path: '/api/cvs/$cvId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cv-builder-chat': typeof ApiCvBuilderChatRoute
  '/api/cv-chat': typeof ApiCvChatRoute
  '/cvs/$cvId': typeof CvsCvIdRoute
  '/cvs/new': typeof CvsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/cvs/$cvId/pdf': typeof ApiCvsCvIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cv-builder-chat': typeof ApiCvBuilderChatRoute
  '/api/cv-chat': typeof ApiCvChatRoute
  '/cvs/$cvId': typeof CvsCvIdRoute
  '/cvs/new': typeof CvsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/cvs/$cvId/pdf': typeof ApiCvsCvIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cv-builder-chat': typeof ApiCvBuilderChatRoute
  '/api/cv-chat': typeof ApiCvChatRoute
  '/cvs/$cvId': typeof CvsCvIdRoute
  '/cvs/new': typeof CvsNewRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/cvs/$cvId/pdf': typeof ApiCvsCvIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/cv-builder-chat'
    | '/api/cv-chat'
    | '/cvs/$cvId'
    | '/cvs/new'
    | '/people/$personId'
    | '/api/cvs/$cvId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/cv-builder-chat'
    | '/api/cv-chat'
    | '/cvs/$cvId'
    | '/cvs/new'
    | '/people/$personId'
    | '/api/cvs/$cvId/pdf'
  id:
    | '__root__'
    | '/'
    | '/api/cv-builder-chat'
    | '/api/cv-chat'
    | '/cvs/$cvId'
    | '/cvs/new'
    | '/people/$personId'
    | '/api/cvs/$cvId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCvBuilderChatRoute: typeof ApiCvBuilderChatRoute
  ApiCvChatRoute: typeof ApiCvChatRoute
  CvsCvIdRoute: typeof CvsCvIdRoute
  CvsNewRoute: typeof CvsNewRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  ApiCvsCvIdPdfRoute: typeof ApiCvsCvIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv-builder-chat': {
      id: '/api/cv-builder-chat'
      path: '/api/cv-builder-chat'
      fullPath: '/api/cv-builder-chat'
      preLoaderRoute: typeof ApiCvBuilderChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cv-chat': {
      id: '/api/cv-chat'
      path: '/api/cv-chat'
      fullPath: '/api/cv-chat'
      preLoaderRoute: typeof ApiCvChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvs/$cvId': {
      id: '/cvs/$cvId'
      path: '/cvs/$cvId'
      fullPath: '/cvs/$cvId'
      preLoaderRoute: typeof CvsCvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvs/new': {
      id: '/cvs/new'
      path: '/cvs/new'
      fullPath: '/cvs/new'
      preLoaderRoute: typeof CvsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cvs/$cvId/pdf': {
      id: '/api/cvs/$cvId/pdf'
      path: '/api/cvs/$cvId/pdf'
      fullPath: '/api/cvs/$cvId/pdf'
      preLoaderRoute: typeof ApiCvsCvIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCvBuilderChatRoute: ApiCvBuilderChatRoute,
  ApiCvChatRoute: ApiCvChatRoute,
  CvsCvIdRoute: CvsCvIdRoute,
  CvsNewRoute: CvsNewRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  ApiCvsCvIdPdfRoute: ApiCvsCvIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
