/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvsCvIdRouteImport } from './routes/cvs.$cvId'
import { Route as PeoplePersonIdRouteImport } from './routes/people.$personId'
import { Route as ApiCvsCvIdPdfRouteImport } from './routes/api/cvs.$cvId.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvsCvIdRoute = CvsCvIdRouteImport.update({
  id: '/cvs/$cvId',
  path: '/cvs/$cvId',
  getParentRoute: () => rootRouteImport,
} as any)
const PeoplePersonIdRoute = PeoplePersonIdRouteImport.update({
  id: '/people/$personId',
  path: '/people/$personId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCvsCvIdPdfRoute = ApiCvsCvIdPdfRouteImport.update({
  id: '/api/cvs/$cvId/pdf',
  path: '/api/cvs/$cvId/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cvs/$cvId': typeof CvsCvIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/cvs/$cvId/pdf': typeof ApiCvsCvIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cvs/$cvId': typeof CvsCvIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/cvs/$cvId/pdf': typeof ApiCvsCvIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cvs/$cvId': typeof CvsCvIdRoute
  '/people/$personId': typeof PeoplePersonIdRoute
  '/api/cvs/$cvId/pdf': typeof ApiCvsCvIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cvs/$cvId' | '/people/$personId' | '/api/cvs/$cvId/pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cvs/$cvId' | '/people/$personId' | '/api/cvs/$cvId/pdf'
  id:
    '__root__' | '/' | '/cvs/$cvId' | '/people/$personId' | '/api/cvs/$cvId/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvsCvIdRoute: typeof CvsCvIdRoute
  PeoplePersonIdRoute: typeof PeoplePersonIdRoute
  ApiCvsCvIdPdfRoute: typeof ApiCvsCvIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvs/$cvId': {
      id: '/cvs/$cvId'
      path: '/cvs/$cvId'
      fullPath: '/cvs/$cvId'
      preLoaderRoute: typeof CvsCvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people/$personId': {
      id: '/people/$personId'
      path: '/people/$personId'
      fullPath: '/people/$personId'
      preLoaderRoute: typeof PeoplePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cvs/$cvId/pdf': {
      id: '/api/cvs/$cvId/pdf'
      path: '/api/cvs/$cvId/pdf'
      fullPath: '/api/cvs/$cvId/pdf'
      preLoaderRoute: typeof ApiCvsCvIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvsCvIdRoute: CvsCvIdRoute,
  PeoplePersonIdRoute: PeoplePersonIdRoute,
  ApiCvsCvIdPdfRoute: ApiCvsCvIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
